README.md

Tiny typo on readme

---

README.md
src/index.tsx
src/use-prevent-scroll.ts
website/src/app/components/hero.tsx

- Fixes https://github.com/emilkowalski/vaul/issues/9
- Adds `fixedHeight` prop
- Fixes scrollIntoView function
- Adjust the logic responsible for resizing when keyboard opens sothat it calculates the correct top offset.

Improve resizing, scroll into view only if needed, add `fixedHeight` prop, fix firefox bug

---

README.md
src/index.tsx

changed `treshold` → `threshold` everywhere

fix: prop typo

---

src/index.tsx
src/use-position-fixed.ts

We need to run `onScroll` at the beginning without scrolling as well.

Fix scroll to top bug

---

src/index.tsx
website/src/app/components/hero.tsx

Dampen drag value

---

src/index.tsx
src/use-position-fixed.ts

We don't need a `setTimeout` after all

ensure scroll gets re-enabled after closing

---

src/index.tsx
src/use-snap-points.ts
website/src/app/components/hero.tsx

Fixes https://github.com/emilkowalski/vaul/issues/117
Also polishes the overlay fade behavior and scenarios where the drawer is scrollable on the last snap point.

Polish snap points

---

src/use-position-fixed.ts

Don't apply fixed positioning when unmounting

---

src/use-snap-points.ts

Fix: Fixed overlay snap bug #171

---

src/index.tsx

Fixes https://github.com/emilkowalski/vaul/issues/236

fix: using e.preventDefault to prevent drawer from closing

---

website/src/app/layout.tsx

- https://github.com/emilkowalski/vaul/issues/224

remove duplicated main element

---

package.json
pnpm-lock.yaml
src/use-snap-points.ts

- https://github.com/emilkowalski/vaul/issues/234

[maintenance]: bump packages

---

src/use-position-fixed.ts

The `fixed` prop lags the drawer when dynamically changing the modal prop

fix: missing dependencies on fixed position hook effect

---

src/index.tsx

Closes https://github.com/emilkowalski/vaul/issues/262
https://github.com/emilkowalski/vaul/assets/23730762/03f51380-2fcd-4aa2-9ef2-5a7772287fbd
https://github.com/emilkowalski/vaul/assets/23730762/989068fa-0eb7-442a-9a87-d2df5427e3e8

Cancel current drag when closing the drawer

---

src/helpers.ts

Added Element existence check, fixes this issue
https://github.com/emilkowalski/vaul/issues/305

fix element existence check

---

src/index.tsx

#259: provide the option to set the background color when `shouldScaleBackground` is set to true.

added setBackgroundColorOnScale prop

---

src/index.tsx

fix(src): Replace `React.useLayoutEffect` with `useIsomorphicLayoutEffect`

---

.github/workflows/playwright.yml
package.json
pnpm-lock.yaml

Upgrade bunchee for performance improvement

build: upgrade bundler

---

src/index.tsx

add export on each props for help developer extends the props on thier custom components

feat: add export on props

---

src/index.tsx

fix: reset scroll behavior

---

src/index.tsx

Prevents auto focusing on inputs etc.

feat: Don't autofocus within Dialog

---

src/index.tsx

fix: ensure interaction after closing

---

src/index.tsx
src/use-prevent-scroll.ts

Also ensure that `repositionInputs` prop is working correctly.

fix: inputs repositioning

---

src/context.ts
src/index.tsx
test/src/app/scrollable-with-inputs/page.tsx

Add `autoFocus` prop and fix `dismissible` logic.

feat: add autofocus prop

---

src/index.tsx

fix: pointer events none 

---

src/index.tsx

Mostly copy-paste from readme with small additions

feat: Add JSDocs

---

src/style.css
test/src/app/different-directions/page.tsx
test/src/app/page.tsx

This will allow consumers to adjust the initial transform value in case you need a drawer with a side offset.

feat: add initial transform css variable

---

src/index.tsx

Fix `useCallback` to not be conditionally rendered
