emilkowalski/vaul

README.md
src/index.tsx

A user that tries to close the drawer within one second after scrolling inside content will be prevent from dragging the drawer. However if the user is impatient/confused and keeps trying to close the drawer, they will be endlessly stuck in a non-draggable drawer since the timer resets on every attempt. This PR fixes this timer reset and also exposes the timeout duration as an option since it was desirable for our project to tweak this timing and thus might be valuable to others too.
This PR:
- fixes the endlessly stuck drawer issue
- introduces an optional prop to control the scroll lock timeout

add scroll lock timeout option and fix endless drag prevention

---

README.md
src/index.tsx

The close threshold was not handled correctly and was causing issues with clicks/taps. When clicking on the sheet at a y-coordinate below the close threshold, the sheet would close. Expected behaviour is that it only closes after dragging, not on clicks and that it should close when the user swipes more than `closeThreshold * visibleDrawerHeight` regardless of the click/tap y-coordinate.
A video of the bug is attached below (note that we need to drag the sheet up first, because the bug only happens when `--swipe-amount` is set on the sheet)
https://github.com/emilkowalski/vaul/assets/9706105/21c29671-94a6-4fc6-ae9c-263637efc341

fix closeThreshold bug

---

src/index.tsx
website/src/app/components/hero.tsx

Before, the swipe could close the drawer right when you reached the top of a scrollable container, which could be unintentional. Right now we have a treshold of 500ms before we actually allow to drag down after we reach the top.

Improve swiping in a scrollable drawer

---

src/index.tsx
src/style.css
src/use-prevent-scroll.ts

This PR does the following:
- Refactors the drag logic to use transform directly instead of a css variable. This drastically improves performance when the content of the drawer becomes more complex. [See this for more context](https://lisilinhart.info/posts/css-variables-performance/).
- Makes the body fixed when the drawer opens to ensure the Safari toolbar becomes visible to avoid a gnarly shift when the drawer opens and the toolbar wasn't visible initially.
- A couple of improvements to when a dsrawer is scrollable, before, swiping upwards in a scrollable drawer wasn't possible for example.

Performance and scroll improvements

---

src/index.tsx
website/src/app/components/hero.tsx

`initialViewportHeight` was obsolete, we just need to grab `window.innerHeight` to get the height without accounting for keyboard.

Improve keyboard calculations

---

src/index.tsx

The cache here will retain the reference to the DOM node, change it to weakmap so that the memory will be managed automatically when the DOM node disappears

fix: use WeakMap instead of Map to avoid memory leaks

---

src/index.tsx

The height of the keyboard itself can change during typing as well. This was causing the drawer to recalculate the bottom and height values incorrectly. Now we check whether the height has changed by more than `60`, if that is the case, we know that the keyboard has been hidden/shown.

Fix visual viewport height calculation

---

src/index.tsx
website/src/app/components/hero.tsx

Optimizes perf as well by not running shouldDrag on each drag.

Improve scrolling, don't run shouldDrag on each drag

---

pnpm-lock.yaml
src/index.tsx
website/package.json

Previously when the menu was closed due to a changed in the `open` prop the drawer would close instantly.

Close menu properly when controlled

---

src/index.tsx

Bug where you were allowed to drag permantently after scrolling on iOS. This was because iOS doesn't fire mouseUp event after scrolling, we fix it by listening to `touchend` once after pressing.

Fix iOS mouse-up after scrolling

---

src/index.tsx

Unmount without closing the drawer resulted in bugged wrapper state.

Cleanup wrapper styles on unmount

---

src/index.tsx
src/use-position-fixed.ts

This PR makes it so that the position is properly reset whenever the drawer is unmounted.
@emilkowalski You can use this page for testing (although you need to unset the `overflow: hidden`'s on the body in `globals.css`).
[page.txt](https://github.com/emilkowalski/vaul/files/12804900/page.txt)
Fixes #135.

fix: restore position setting on unmount #135

---

src/use-snap-points.ts
test/src/app/initial-snap/page.tsx
test/src/app/page.tsx
test/src/app/route-based-drawer/page.tsx
test/tests/initial-snap.spec.ts

Fixes issues snapping to initial value if it is not equal to 0 #146 
Added route with example showing the issue

fix: snap to initial value not equal to 0

---

src/index.tsx
src/use-position-fixed.ts

Previously when the url has been changed due to a navigation within the drawer, scroll position was still getting restored to the one from when you opened the drawer, we don't want that when navigating.
Also disabling multi touch support for now to bring back better scroll behavior.

Fix no scroll upon navigation

---

src/index.tsx

The issue in #151 is caused by the `event.clientY` which is negative the second time the drawer opens on Safari after scrolling (for whatever reason...). Changing this value to `event.screenY` fixes the issue as can be seen in the before/after video attached below (sorry, it's hard to read due to the 10mb upload limit 😅).
If you want to test this yourself, see [this branch](https://github.com/andrejilderda/vaul/tree/fix/unable-to-close-drawer-on-ios-under-certain-circumstances-testsuite).
https://github.com/emilkowalski/vaul/assets/487182/797f3a57-425f-4994-addb-0d93502ddcb9
Note: 5 E2E tests fail, but this is also the case for `develop`.

fix: rely on screenY in stead of clientY for determining drag distance

---

src/use-snap-points.ts

There's currently a bug I noticed that lets the drawer exceed the snap points boundaries. You can reproduce this by dragging down and as soon as the animation starts, switch to dragging up (without releasing). Is there any use case where this might be needed? If so maybe we can introduce a prop. Let me know
Sandbox: https://codesandbox.io/p/devbox/drawer-snap-points-forked-3xxclj?file=%2Fapp%2Fmy-drawer.tsx
Video: https://www.loom.com/share/db36353318114dedb964d320be8849fc?sid=05234bb7-f938-4666-aba4-b57bd1e993ae

Fix: Prevent sheet from exceeding boundaries of the last snap point while dragging

---

src/use-snap-points.ts

With the addition of other directions, there's currently a breaking change where we're referencing a value that doesn't exist (`newYValue`). This will fix that and also check if boundaries are exceeded on all directions

Fix: Update snap points boundaries check to also deal with top and left directions

---

src/use-snap-points.ts

Fixes #222 
The condition [here](https://github.com/emilkowalski/vaul/pull/223/files#diff-0ac317dea14b2b9b41020d54607d198389fc65de549dc798887b683418755d48L119) checks that `newIndex` is not null by truthiness, but it could fail when `newIndex` is 0 (which is a valid value) as well.
I've changed the fallback value of `newIndex` to -1 to be inline with `findIndex` returning -1 when there is no match, and updated the check accordingly.

Fix: Allow snapping to the first snap point

---

src/use-snap-points.ts

Fixes #225 
In `activeSnapPointOffset ?? 0 - draggedDistance`, `-` has more precedence than `??`, so it evaluates to `activeSnapPointOffset ?? (0 - draggedDistance)`, causing `currentPosition` to always be the active snap point regardless of the dragged distance.

Fix useSnapPoints onRelease position

---

src/index.tsx

- https://github.com/emilkowalski/vaul/issues/228
- https://github.com/emilkowalski/vaul/issues/188

cleanup bg on body

---

package.json
pnpm-lock.yaml
test/package.json
test/tsconfig.json
tsconfig.json
website/package.json
website/tsconfig.json

* Move build related dependencies to "devDependencies"
* Align the `@types/react` and `@types/react-dom` version to the ones that needed for ts 5.2.2

chore: move build related to dev deps

---

src/index.tsx

Currently, `data-vaul-no-drag` only worked if the dragged element is exactly the element that has the attribute. The expected behavior is it works if any of the parent (using `element.closest`) has the attribute. Fixes #266

Make data-vaul-no-drag work if any parent matches

---

src/index.tsx

Fix a UI issue where the user is unable to drag the drawer in the _open_ direction—up is the default, for example—when the first snap point is active. The fix ensures the user cannot drag beyond the first snap point on close, but can drag open smoothly. It also removes the issue/bug where the user can drag beyond the first snap point when another snap point is active.
```
<Drawer.Root dismissible={false} snapPoints={[0.2, 1]} modal={false}>
...
</Drawer.Root>
```

Fix Non-Dismissable Swiping

---

pnpm-lock.yaml
src/index.tsx
src/style.css

Fixes #295 
This PR blocks the swipe if the user starts swiping in the wrong direction allowing the user to select text within the vaul. Unfortunately this fix will only work for pointers. It was not possible to fix it for mobile because I realized that the problem comes from the `react-remove-scroll` lib that Radix uses under the hood to block scrolling.
Also forwards some events from the `DialogPrimitive.Content` props
https://github.com/emilkowalski/vaul/assets/48808846/62a062b7-579f-4e54-93ed-7235f423f788
https://github.com/emilkowalski/vaul/assets/48808846/1e54e09a-dba3-4011-9a9e-49a1f42b23c6

fix: block swipe if in wrong direction

---

src/use-position-fixed.ts

I simply added a new condition to only call setPositionFixed when display mode is set to standalone like in most PWA's.
Solves #199 where you can find more details about the problem. I personally don't think this needs an extra prop for more control over this behaviour but maybe there is a good reason for including one?

Fix position fixed causing layout shifts on standalone sites (pwa)

---

src/helpers.ts
src/use-position-fixed.ts

Updating multiple inline styles at once can be done more efficiently with Object.assign. This portion of code was causing quite a few recalculation renders on some browsers

Batch fixed position style updates

---

pnpm-lock.yaml
src/index.tsx
website/src/app/test-modal/_page/hero.tsx
website/src/app/test-modal/page.tsx

fixes #331 and follows on #109
added preventDefault to onFocusOutside() and onEscapeKeyDown()
website: added 'test-modal' route with demo of issue / fix
Without the added code, clicking on the 'Does nothing' button, (or any focasable element) will close the drawer, even if non-modal.
Without the added code, hitting the ESC key will close the drawer, even if non-modal. 
tl;dr:
#109 handled one of case that closes the drawer by default, but not the other two:
https://github.com/radix-ui/primitives/blob/main/packages/react/dismissable-layer/src/DismissableLayer.tsx
```typescript
const pointerDownOutside = usePointerDownOutside((event) => {
const target = event.target as HTMLElement;
const isPointerDownOnBranch = [...context.branches].some((branch) => branch.contains(target));
if …
```

Fix inappropriate non-modal drawer closure

---

src/use-snap-points.ts

Fixes #398 
https://github.com/user-attachments/assets/2fd21e6a-1043-472c-b32b-d35afafb076d
Please let me know if this needs more work!

adjust snapPoints on window resize

---

src/index.tsx

When trying to use Vaul in a component library that also re-exports TypeScript types (via something like `vite-plugin-dts`), type generation would fail with an external module error:
```
error TS4023: Exported variable 'Root' has or is using name 'WithFadeFromProps' from external module "/%project%/node_modules/vaul/dist/index" but cannot be named.
```
Marking `DialogProps` with an `export` keyword fixes this issue. There's also a bonus of not having to use `React.ComponentProps<T>` when the type is properly exported from the library.

Export DialogProps type

---

README.md
src/index.tsx
src/style.css
test/src/app/controlled/page.tsx
test/src/app/nested-drawers/page.tsx
test/src/app/non-dismissible/page.tsx
test/src/app/scrollable-with-inputs/page.tsx
test/src/app/with-scaled-background/page.tsx
test/src/app/without-scaled-background/page.tsx
test/tests/base.spec.ts
test/tests/initial-snap.spec.ts
test/tests/non-dismissible.spec.ts
test/tests/with-scaled-background.spec.ts
test/tests/without-scaled-background.spec.ts
website/src/app/layout.tsx

Related issue: [369](https://github.com/emilkowalski/vaul/issues/369)
- This PR makes vaul use common data-attribute for content direction. This allows usage of Tailwind classes to style the Drawer differently for different directions.
- The typo `vault` is fixed in `style.css`

ISSUE-369: Make vaul use data- attr for Content direction

---

.gitignore
README.md
package.json

The css file was output by tsup into the `dist/` before, this PR manually copy the css into `./style.css` since there're users relying on it already.
Updated the readme to clarify the usage. This could be a workaround solution for users having CSP restrictions
Closes #283
Closes #357

Contain CSS file in the published package

---

src/index.tsx

This fixes issue when `Drawer` without `Drawer.Overlay` while having `modal={false}`
This fix should also not break when `Drawer.Overlay` is passed
Without `Drawer.Overlay`
```tsx
<Drawer.Root modal={false}>
<Drawer.Trigger>Open</Drawer.Trigger>
<Drawer.Portal>
<Drawer.Content>
<p>Content</p>
</Drawer.Content>
</Drawer.Portal>
</Drawer.Root>
```
With `Drawer.Overlay`
```tsx
<Drawer.Root modal={false}>
<Drawer.Trigger>Open</Drawer.Trigger>
<Drawer.Portal>
<Drawer.Content>
<p>Content</p>
</Drawer.Content>
<Drawer.Overlay />
</Drawer.Portal>
</Drawer.Root>
```

fix: Fix non-modal drawers without overlay to properly set body pointer events

---

src/use-position-fixed.ts
test/src/app/page.tsx
test/src/app/with-redirect/long-page/page.tsx
test/src/app/with-redirect/page.tsx
test/tests/with-redirect.spec.ts

In previous versions (~0.9.2) the restore position settings was executed in the useEffect unmount trigger: https://github.com/emilkowalski/vaul/blob/3510ebdfc35a67a6c7ec8ea66386dbaf0e1b941e/src/index.tsx#L347-L352
The new version is going to only restore based on the `onChange`, which is fine and works better for most of the situations, **but** it fails to restore during a redirect/click in a link inside of the drawer.
https://github.com/emilkowalski/vaul/blob/5cd388cfb5d9bf1664d27fc280839562dd79297c/src/index.tsx#L172-L176
Added a new playright example:
It only affects iphone, after redirect the body is going to still have the position fixed, preventing any scroll:
I added a new solution trying to improve the unmount trigger, no changes to the `onChange` flow, but during the unmount if …

fix: restore position settings on drawer unmount

---

src/context.ts
src/index.tsx
src/use-prevent-scroll.ts
src/use-snap-points.ts
tsconfig.json

fixes https://github.com/emilkowalski/vaul/issues/476
the root cause was about a missing check caused by event possibly null, suggesting to keep `strict: true` in tsconfig to help prevent these bugs, included the fixes to keep it on.

fix: typescript strict on to prevent null calls

---

src/context.ts
src/index.tsx

When setting `activeSnapPoint `to any value other than the first element in the `snapPoints `array, the drawer component always initializes at the first snap point on the initial render. It only updates to the correct `activeSnapPoint `after an external re-render occurs. This behavior is due to how the initial style is assigned and how `snapPointsOffset `is calculated when the component first mounts. 
This can be recreated by running the repo localy, and try to use `/initial-snap` test route. This does not work of the bat (it will open drawer with offset for the first element in the `snapPoints `array), but opening `initial-snap/page.tsx`, and saving any change, will force a re-render which will then open the drawer at the correct snap point.
The `DialogPrimitive.Content` component …

Fix: Ensure drawer opens at the specified active snap point on initial render

---

src/browser.ts
src/index.tsx
src/use-position-fixed.ts
src/use-prevent-scroll.ts

Also create a `browser.ts` file for better structure.

fix: mobile firefox inputs

---

src/index.tsx

fix: initial nested transform

---

src/index.tsx

This appears to fix the open issue
[Nested drawer doesn't fire onOpenChange callback #457](https://github.com/emilkowalski/vaul/issues/457)
And also allows for the nested drawer to be controlled independently via `nestedIsOpen`
I noticed that the onOpenChange got removed in this commit
https://github.com/emilkowalski/vaul/compare/v0.9.2...v0.9.4#diff-0b5adbfe7b36e4ae2f479291e20152e33e940f7f265162d77f40f6bdb5da7405L1071
For my use case I also needed to open a nested drawer on route change, I've attached a short video to illustrate what I mean.
https://github.com/user-attachments/assets/82d9b87f-18bd-4617-94dc-369b80256efe
For info: to ensure that the parent drawer transitions correctly when the nested drawer is opened on route change I also needed to add this code
```js
React.useEffect(() …
```

fix: nested drawer onOpenChange issue
